### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Tr4il** [weafon/vmfs6-tool#1]
I'm having issues building this on Ubuntu. Would you be able to provide an installable binary?
I'd apprecitate it. Thanks!

**Comment by ghost** [comment]
Yes it would really help us

**Comment by ghost** [comment]
@Tr4il I builded the code on ubuntu and it was easy

**Comment by IOAyman** [comment]
@Tr4il [Requirements] are very few.


[Requirements]:https://github.com/glandium/vmfs-tools/blob/4ab76ef5b074bdf06e4b518ff6d50439de05ae7f/README

**Comment by bridgeythegeek** [comment]
For me, on `Ubuntu 18.04.1`...
```
sudo apt install build-essential libfuse-dev uuid-dev
```
was all I needed.

**Comment by kfordaccela** [comment]
> For me, on `Ubuntu 18.04.1`...
> 
> ```
> sudo apt install build-essential libfuse-dev uuid-dev
> ```
> 
> was all I needed.

I haven't been able to make this work for my debian install. Hoping that we can get this worked out.
