### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by kfordaccela** [weafon/vmfs6-tool#2]
Having issues doing a build on Debian

##System##> make
gcc -DVMFS_DEBUG=0 -DVMFS_DEBUG=0 -Wall -O2 -g -D_FILE_OFFSET_BITS=64 -DNO_STRNDUP=1 -Idebugvmfs -Ilibvmfs -I/usr/include/uuid -Ilibreadcmd  -include version   -c -o debugvmfs/debugvmfs.o debugvmfs/debugvmfs.c
In file included from libvmfs/vmfs.h:53,
                 from debugvmfs/debugvmfs.c:31:
libvmfs/utils.h:195:21: error: static declaration of ‘strndup’ follows non-static declaration
 static inline char *strndup(const char *s, size_t n) {
                     ^~~~~~~
In file included from debugvmfs/debugvmfs.c:22:
/usr/include/string.h:174:14: note: previous declaration of ‘strndup’ was here
 extern char *strndup (const char *__string, size_t __n)
              ^~~~~~~
make: *** [<builtin>: debugvmfs/debugvmfs.o] Error 1

**I ended up giving up on this and just moving my data another way, wish that it would have worked.**

**Comment by weafon** [comment]
I guess the error results from the strict check of the latest gcc. If you replace "const char *s" with "const char *__string", is the error fixed?

**Comment by zablah** [comment]
I have the same error, even after eplace "const char *s" with "const char *__string"
also I tried to use gcc6 and the same error

**Comment by akhepcat** [comment]
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

Builds correctly, fwiw.
